apiVersion: v1
kind: Service
metadata:
  name: {{ include "ros-drone-demo.fullname" . }}-zenoh
  labels:
    {{- include "ros-drone-demo.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "ros-drone-demo.name" . }}-zenoh
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: zenoh
      port: {{ .Values.zenoh.servicePort }}
      targetPort: zenoh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ros-drone-demo.fullname" . }}-zenoh
  labels:
    {{- include "ros-drone-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ros-drone-demo.name" . }}-zenoh
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ros-drone-demo.name" . }}-zenoh
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: zenoh
          image: {{ .Values.images.zenoh | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: zenoh
              containerPort: {{ .Values.zenoh.servicePort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
